napframework/nap

- modules/napapp/src/apprunner.h
- modules/napaudio/src/audio/core/audiopin.cpp
- modules/napaudio/src/audio/core/audiopin.h
- modules/napaudio/src/audio/node/mixnode.cpp
- modules/napaudio/src/audio/node/mixnode.h
- modules/napaudio/src/audio/node/multiplynode.cpp
- modules/napaudio/src/audio/node/multiplynode.h
- modules/napaudio/src/audio/service/audioservice.cpp
- modules/napaudio/src/audio/service/audioservice.h
- modules/napaudio/src/audio/utility/safeptr.cpp
- modules/napaudio/src/audio/utility/safeptr.h
- modules/napparameter/src/parameternumeric.h
- modules/napparameter/src/parametersimple.h
- modules/napparameter/src/parametervec.h
- utility/src/utility/threading.cpp
- utility/src/utility/threading.h
These are a couple of changes to the NAP repository made by 4DSOUND:
these will concern Naivi most:
- The AppRunner shuts down the services when the initialization fails, to ensure shutdown() is always called when init() has succeeded.
- The Parameter::setValue() functions are exposed to rtti, so they can be called form python scripts.
And these less so, as they are mainly audio changes:
- The signature of audio::MultiInputPin::pull() method has changed, so the caller has the responsibility to manage the destination buffer. This solves some threadsafety concerns while parallel processing audio.
- The host API index is passed to AudioService::openStream() method, to make sure it is updated internally when the device settings change at runtime.
- A simplification in the …
> 4dsound nap pr january 2020

- modules/napaudio/src/audio/component/inputcomponent.cpp
- modules/napaudio/src/audio/service/audioservice.cpp
These are some bugfixes that I advice to merge into main private as well as public:
- Fix error in sample rate logging formatting by AudioService
- Fix error in property rtti definition in AudioInputComponent
> Napaudio fixes feb 2021

- demos/audioplayback/config.json
- demos/audioplayback/project.json
- modules/napaudio/src/audio/service/audioservice.cpp
- modules/napaudio/src/audio/service/audioservice.h
- More clear logging of audio devices and channel settings on startup
- Extra config setting for the audio service to be able to create input-only audio apps: DisableOutputs
> Audioservice logging

- system_modules/napportaudio/src/audio/service/portaudioservice.cpp
- system_modules/napportaudio/src/audio/service/portaudioservice.h
This overload is necessary to be able to request device info with a global index (not relative to the host index)
> overload PortAudioService::getDeviceInfo()

- system_modules/napportaudio/src/audio/service/portaudioservice.cpp
- fix openStream errors when inputChannelCount = 0 but deviceSettings.mDisableInput == true (default), same goes for outputChannelCount
- fix openStream error where inputChannelCount and outputChannelCount were not copied by deviceSettings
> fix portaudio incorrect PortAudio openStream errors 

- styleguide/styleguide.md
- system_modules/napvideo/src/video.cpp
- system_modules/napvideo/src/video.h
- system_modules/napvideo/src/videoplayer.cpp
- system_modules/napvideo/src/videoplayer.h
- This PR aims to fix a problem where video looping and seeking would not be consistent. The seek operation was discarding the seek frames, resulting in those frames to be skipped altogether and also causing synchronization issues when playing two seperate videos that need to be in sync
- Added a bool arg for video play giving the user the option to not clear the previous textures. This prevents black or green textures from being rendered when calling play or switching videos
To test : Build and run videomodulation demo, observe the perfectly looping video
> napvideo improvements

- core/src/nap/signalslot.h
- system_modules/naprender/src/renderablemesh.cpp
- system_modules/naprender/src/renderablemesh.h
This PR fixes the following issue: When a renderable mesh is copied the connections of the `RenderableMesh::mVertexBufferDataChangedSlot` are copied as well, but the original causes (connections) are not cleared. This causes the list of connections to grow every time a `nap::RenderableMesh` is copy assigned or copy constructed. This wasn't noticable because most renderable meshes are created on init and remain static. Only when creating (many) renderable meshes at runtime (on update for example) could this be noticeable. 
To fix this I made every `nap::Slot<T>` copy and move assignable, where current connections are cleared before the other connections are copied. An added benefit of the move assignment operator is that the referenced vertex data is now moved instead of copied - lowering …
> RenderableMesh copy fix & improvement

- tools/napkin/src/document.cpp
- tools/napkin/src/document.h
Small improvement for: https://github.com/napframework/nap/pull/37
- Only allow deep copy of rtti::Object* and and copy constructable rtti structs
- Ensure that when we deep copy an object pointer it is of type: nap::rtti::Object
- Cleanup
> Only allow deep copy of rtti::Object* and RTTI enabled structs

- system_modules/naprender/src/renderwindow.cpp
- system_modules/naprender/src/renderwindow.h
- system_modules/naprender/src/sdlhelpers.cpp
- system_modules/naprender/src/sdlhelpers.h
This PR fixes [setFullScreen on windows and linux](https://github.com/napframework/nap/issues/33)
The main culprit was inside `RenderWindow::beginRendering()`, where it would use the current window bounds instead of the swap chain extend for setting up the render pass, causing the subsequent vulkan render calls to fail when (out of session) the window was resized, because the render-window could be larger than the allocated surface.
By making sure the render area matches the assigned swap-chain-extent we know for sure the render pass will succeed, but updating the display queue or requesting an image index could fail because the surface could be out of sync with the swap-chain , but that's ok: we take that as a hint for re-creating the swapchain the next frame.
As a safety I also handle …
> Fullscreen fix

- system_modules/napaudio/src/audio/component/levelmetercomponent.h
- system_modules/napaudio/src/audio/node/levelmeternode.cpp
- system_modules/napaudio/src/audio/node/levelmeternode.h
I accidentally omitted a square root when rewriting the RMS implementation in LevelMeterNode. With this PR it is re-added.
I decided to add the sqrt() call in the getter to not impact audio thread performance.
> Fix RMS calculation

- system_modules/naprender/src/shader.cpp
Assert with useful error message when shader file includer fails. Return from `releaseInclude` instead of empty `assert`, `glslang` asserts with a more descriptive error message later as well.
> Output useful error message when shader file includer fails

- system_modules/napmath/src/mathattributes.cpp
- system_modules/naprender/src/bufferbindinginstance.cpp
- system_modules/naprender/src/formatutils.cpp
- system_modules/naprender/src/gpubuffer.cpp
- system_modules/naprender/src/gpubuffer.h
- system_modules/naprender/src/mesh.cpp
- system_modules/naprender/src/shadervariabledeclarations.h
- system_modules/naprender/src/uniforminstance.cpp
- system_modules/naprender/src/vertexattribute.cpp
- system_modules/naprender/src/vertexattribute.h
Useful for (signed) integer storage buffers that require 16-byte alignment
> RTTI Register ivec4 and add GPUBufferIVec4

- system_modules/naposc/src/oscsender.cpp
- system_modules/naposc/src/oscsender.h
This PR fixes a crash that can occur when UdpTransmitSocket constructor throws an exception. This can happen when there is no network connection. Also, it adds a `AllowFailure` property to the OSCSender that allows the OSCSender to initialize even when this happens.
Steps to test this PR
- Disconnect computer from any network, wireless or wired
- Changed to IP of the `OSCSender` resource in the OSCMidi demo to something that looks like a network address (like `168.122.33.44`)
- Run OSCMidi
- Observe application not initializing
- Open OSCMidi demo project json with Napkin
- Set `AllowFailure` property in the `OSCSender` resource to true
- Run OSCMidi
- Observe application initializing and log an error
> Fix crash in OSCSender when UdpTransmitSocket throws uncaught exception in constructor

- system_modules/naprender/src/computecomponent.cpp
This assert is triggered if the group count of the requested compute task exceeds the [physical device limit](https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDeviceLimits.html). This violation of the spec is caught by the Validation layers but I thought it would be useful to provide this warning with added context this way.
> Assert compute workgroup count on dispatch

- demos/audiovisualfft/app.json
- demos/audiovisualfft/build.sh
- system_modules/napaudio/module.json
- system_modules/napfft/module.json
- system_modules/napportaudio/module.json
- system_modules/naprender/src/renderservice.cpp
I think it would make more sense if the `Additive` blend function takes source alpha into account. This will resolve the same final color independent of ordering. Below an example where I'm rendering point sprites with alpha as a distance function in the fragment shader.
Original additive blending:
```
srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
dstAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
srcColorBlendFactor = VK_BLEND_FACTOR_ONE;
dstColorBlendFactor = VK_BLEND_FACTOR_ONE;
```
Updated additive blending:
```
srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
dstAlphaBlendFactor = VK_BLEND_FACTOR_ZERO;
srcColorBlendFactor = VK_BLEND_FACTOR_SRC_ALPHA;
dstColorBlendFactor = VK_BLEND_FACTOR_ONE;
```
This update could change the look of existing projects. Alternatively we could add this under the name …
> Update additive blend mode to multiply alpha

- tools/napkin/src/standarditemsobject.cpp
Fixes bug (#88) where the object type in Napkin is not updated after swapping (moving) indices. Every column of a row is now swapped, instead of just the main one (0).
> Napkin index swap fix

- system_modules/naprender/src/renderwindow.cpp
- system_modules/naprender/src/renderwindow.h
- system_modules/naprender/src/sdlhelpers.cpp
- system_modules/naprender/src/sdlhelpers.h
- tools/napkin/src/main.cpp
Add `nap::RenderWindow::AlwaysOnTop` property to move a window to the front and keep it there. This property can also be set as a flag at runtime through: `nap::RenderWindow::setAlwaysOnTop()`.
> Add always on top window flag

- system_modules/napmidi/src/midiport/midiinputport.cpp
- system_modules/napmidi/src/midiport/midiinputport.h
- system_modules/napmidi/src/midiport/midioutputport.cpp
- system_modules/napmidi/src/midiport/midioutputport.h
Fixes (backwards compatibility?) problem with ctors in MidiInputPort and MidiOutputPort that causes the pointer to the MidiService not to be set.
> MidiInputPort and MidiOutputPort fix

- system_modules/naprender/src/renderwindow.cpp
- system_modules/naprender/src/renderwindow.h
After updating the Vulkan SDK to 1.4.313 the validation layer reported the following issue (AMD Radeon 9070XT, Windows 11):
```
[error] vkQueueSubmit(): pSubmits[0].pSignalSemaphores[0] (VkSemaphore 0xbe00000000be) is being signaled by VkQueue 0x25b807309b0, but it may still be in use by VkSwapchainKHR 0xae00000000ae.
Here are the most recently acquired image indices: [0], 1, 2.
(brackets mark the last use of VkSemaphore 0xbe00000000be in a presentation operation)
Swapchain image 0 was presented but was not re-acquired, so VkSemaphore 0xbe00000000be may still be in use and cannot be safely reused with image index 2.
Vulkan insight: One solution is to assign each image its own semaphore. Here are some common methods to ensure that a semaphore passed to vkQueuePresentKHR is not in use and …
```
> Render Window synchronization fix & optimization

- system_modules/naprender/src/renderwindow.cpp
- system_modules/naprender/src/renderwindow.h
Create vulkan sync primitives (semaphores) based on number of allocated swap-chain images, not minimum required. Should fix https://github.com/napframework/nap/issues/100.
The number of swap-chain images created by Vulkan doesn't have to match the minimum number of requested swap-chain images when calling `VkSwapchainCreateInfoKHR` (`RenderWindow::createSwapChain`). Vulkan is free to allocate a higher number of swap-chain images than requested, in that case the index returned by `vkAcquireNextImageKHR` could (will) exceed the size of the current semaphore submission array, because that array is created based on the requested count, not the number of image handles returned by the `VkSwapchainCreateInfoKHR` call.
I also added an `assert` if the requested index is out of bounds and moved the …
> create sync primitives based on number of allocated swap-chain images
